const std = @import("std");
const ag = @import("../interpreter/abi/grammar.zig");
const util = @import("../util.zig");

const auto_generated_tag =
    \\//This file is auto-generated by tools/gen_abi_spec.zig
;

const usage =
    \\Usage: stitch abi-spec <abi json>
    \\
    \\Generates Zig bindings for an ABI specification .json (either core or
    \\extinst versions). The result, printed to stdout, should be used to update
    \\files in src/autogen/specifications. Don't forget to format the output.
    \\
    \\The relevant specifications can be obtained from the Stitch Registry
    \\https://github.com/registry.stitch.com/
    \\
;

const bindings = auto_generated_tag ++
    \\
    \\const Version = @import("std").SemanticVersion;
    \\pub const AbiFunctionType = enum(u8) {
    \\    function = 0x0,
    \\};
    \\pub const AbiComponentType = enum(u8) {
    \\    tuple = 0x10,
    \\    uint256 = 0x11,
    \\};
    \\const AbiFunction = struct {
    \\    name: []const u8,
    \\    type: AbiFunctionType,
    \\    inputs: []AbiComponent,
    \\    outputs: []AbiComponent,
    \\};
    \\const AbiComponent = struct {
    \\    name: []const u8,
    \\    type: AbiComponentType,
    \\    components: []AbiComponent,
    \\};
    \\
    \\
;

pub fn render(allocator: std.mem.Allocator, registry: ag.CoreRegistry) !void {
    _ = registry;

    const file = try std.fs.cwd().createFile(
        "src/autogen/specifications/abi.zig",
        .{ .read = true },
    );
    defer file.close();

    try util.write_to_file(
        file,
        allocator,
        "{s}",
        .{bindings},
    );
}

pub fn print_usage() void {
    std.log.info("{s}", .{usage});
}
